#!/usr/bin/bash                                                                                                                
set -euo pipefail   
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Color Templates || #6F674B #837B5E #998F71 #A89E81 #B5AB8A #C8BE9A #e7e3d5 #9a978a #6F674B #837B5E    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
MOD='MODULES=' ; MKC='/etc/mkinitcpio.conf' ; if [[ "$(lscpu | grep -Eo "Intel" | sort -u)" == Intel ]]
sudo pacman -S git ; git clone https://aur.archlinux.org/pikaur.git ; cd pikaur ; makepkg --fsri ; PKR="pikaur -S"
${PKR} linux-zen-git linux-zen-git-headers linux-firmware-git btrfs-progs-git grub-btrfs-git efibootmgr-git  
then VGA="intel-ucode-git xf86-video-intel-git" && sed -i 's/'${MOD}'()/'${MOD}'(i915 btrfs)/' ${MKC} ; else
VGA="amd-ucode-git xf86-video-amdgpu-git" && sed -i 's/'${MOD}'()/'${MOD}'(amdgpu btrfs)/' ${MKC} ; fi 
printf "${RED}GRAPHIC DRIVERS${NOC}\n" ; ${PKR} VGA ; mkinitcpio -P
printf "${RED}NETWORK ENABLED${NOC}\n" ; systemctl enable NetworkManager
umount /.snapshots/ ; rm -rf /.snapshots/ ; snapper --no-dbus -v list-configs ; snapper --no-dbus -v create-config / 
btrfs subvolume delete /.snapshots ; mkdir /.snapshots ; mount -a ; chmod 750 /.snapshots 
printf "${RED}SNAPSHOT ENABLED ${NOC}\n" ; systemctl enable snapper-timeline.timer ; systemctl enable snapper-cleanup.timer
printf "${RED}GRUB INSTALL ${NOC}\n" ; grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB 
systemctl enable grub-btrfs.path 
GFX='GRUB_GFXMODE=' ; sed -i 's/'${GFX}'auto/'${GFX}'1920x1080,1024x768x32,auto/' /etc/default/grub
SED='ALLOW_USERS=' ; sed -i 's/'${SED}'""/'${SED}'"'${USN}'"/' /etc/snapper/configs/root 
snapper --no-dbus create ; grub-mkconfig -o /boot/grub/grub.cfg
printf "${RED}SYSTEM CLEANUP ${NOC}\n" ; pacman -Sc ; cd / ; chown root:root /home ; chmod 755 /home 
sudo pacman -S git vim ; git clone https://aur.archlinux.org/pikaur.git ; cd pikaur/ ; makepkg --fsri ; echo -n "amd or intel? " ; read PCC 
PKR="pikaur -S --noconfirm" ; ${PKR} "$("{PCC}"-ucode)" "$(xf86-video-"{PCC}")" || pikaur -S --noconfirm "$(xf86-video-"{PCC}"gpu)"
${PKR} alsa-utils pipewire pipewire-alsa pipewire-pulse pipewire-jack gst-plugin-pipewire libpulse volumeicon-git vlc
${PKR} networkmanager-git nm-tray-git grub-git grub-btrfs-git mkinitcpio-btrfs sddm-stellar-theme xdg-user-dirs xdg-utils xorg openbox
${PKR} tint2-git firefox-beta picom-git wpgtk-git profanity-python2-git all-repository-fonts obmenu-generator obkey
${PKR} thunar-git thunar-volman-devel thunar-archive-plugin-git thunar-custom-actions gvfs-git gufw htop acpid
${PKR} alacrity-git vim-youcompleteme-git xterm-git geany-git geany-themes-git geany-plugins-git timeshift-autosnap
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB ; grub-mkconfig -o /boot/grub/grub.cfg 
systemctl enable NetworkManager || systemctl enable avahi-daemon || systemctl enable reflector.timer || systemctl enable libvirtd
systemctl enable acpid || systemctl enable sshd || systemctl enable sddm || wpga-install.sh || echo "openbox-session" >> $HOME/.xinitrc
printf "\e[1;31mDone!\e[0m" ; exit ; umount -a ; reboot
