#!/usr/bin/bash                                                                                                                
set -euo pipefail   
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Color Templates || #6F674B #837B5E #998F71 #A89E81 #B5AB8A #C8BE9A #e7e3d5 #9a978a #6F674B #837B5E    #
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
MOD='MODULES=' ; MKC='/etc/mkinitcpio.conf' ; if [[ "$(lscpu | grep -Eo "Intel" | sort -u)" == Intel ]]
then VGA="intel-ucode-git xf86-video-intel-git" && sed -i 's/'${MOD}'()/'${MOD}'(i915 btrfs)/' ${MKC} ; else
VGA="amd-ucode-git xf86-video-amdgpu-git" && sed -i 's/'${MOD}'()/'${MOD}'(amdgpu btrfs)/' ${MKC} ; fi 
cd ~ ; git clone https://aur.archlinux.org/pikaur.git ; cd pikaur ; makepkg --fsri ; PKR="pikaur -S"
${PKR} linux-zen-git linux-zen-git-headers linux-firmware-git btrfs-progs-git grub-btrfs-git efibootmgr-git  
${PKR} networkmanager-git nm-tray-git sddm-stellar-theme xdg-utils-git xorg-xwayland-hidpi-git openbox
${PKR} alsa-utils-git pipewire-git pipewire-alsa-git pipewire-pulse-git pipewire-jack-git gst-plugin-pipewire-full-git libpulse-hsphfpd volumeicon-git vlc-git
${PKR} tint2-git firefox-beta picom-git wpgtk-git profanity-python2-git all-repository-fonts obmenu-generator obkey-git
${PKR} nemo-git nemo-fileroller-git nemo-preview-git nemo-media-columns-git gvfs-git ufw-bzr htop-git 
${PKR} alacrity-git vim-youcompleteme-git xterm-git geany-git geany-themes-git geany-plugins-git timeshift-autosnap

printf "${RED}SYSTEM CLEANUP ${NOC}\n" ; sudo -S pacman -Sc  ; printf "${RED}NETWORK ENABLED${NOC}\n" ; systemctl enable NetworkManager
printf "${RED}GRUB INSTALL ${NOC}\n" ; GFX='GRUB_GFXMODE=' ; sed -i 's/'${GFX}'auto/'${GFX}'1920x1080,1024x768x32,auto/' /etc/default/grub
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB ; grub-mkconfig -o /boot/grub/grub.cfg
wpga-install.sh ; echo "openbox-session" >> $HOME/.xinitrc
printf "\e[1;31mDone!\e[0m" ; exit ; umount -a ; reboot
